update from the latest that gerbv uses

diff --git a/win32/build_wcalc b/win32/build_wcalc
--- a/win32/build_wcalc
+++ b/win32/build_wcalc
@@ -1,44 +1,7 @@
 #!/bin/sh
 #
-# $Id: build_wcalc,v 1.2 2006/01/03 05:27:51 dan Exp $
+# $Id: build_wcalc,v 1.10 2008/09/03 16:42:25 danmc Exp $
 #
-
-# Copyright (c) 2006, 2007 Dan McMahill
-# All rights reserved.
-#
-# This code is derived from software written by Dan McMahill
-#
-# Redistribution and use in source and binary forms, with or without
-# modification, are permitted provided that the following conditions
-# are met:
-# 1. Redistributions of source code must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
-# 2. Redistributions in binary form must reproduce the above copyright
-#    notice, this list of conditions and the following disclaimer in the
-#    documentation and/or other materials provided with the distribution.
-# 3. All advertising materials mentioning features or use of this software
-#    must display the following acknowledgement:
-#        This product includes software developed by Dan McMahill
-# 4. The name of the author may not be used to endorse or promote products
-#    derived from this software without specific prior written permission.
-#
-# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
-# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
-# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
-# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
-# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
-# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
-# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
-# AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
-# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
-# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
-# SUCH DAMAGE.
-
-
-# Run this under cygwin to build wcalc and create a windows installer for
-# it.  Thanks to Bob Paddock for pointing me to NSIS and answering some 
-# beginner windows questions.
-
 
 # error out on failed commands whose return code wasn't explicitly
 # checked
@@ -56,31 +19,46 @@ Supported options:
 
   --debug         - Omits the compiler flag which prevents
                     a command window from being opened.  This
-                    is useful when trying to use debug printf's
+                    is useful when trying to use debug printf's.
+                    If listed twice then --enable-debug is passed
+                    down to the configure script which enables 
+                    a good bit of debug output.
 
   --help          - Show this message and exit.
 
+  --force-autogen - Force running ./autogen.sh.  Normally this is
+                    only done if the configure script is not present.
+
   --skip-build    - Skip the "make" step of the process.
+
+  --skip-clean    - Skip the "make clean" step of the process.
 
   --skip-config   - Skip the "./configure" step of the process.
 
   --skip-install  - Skip the "make install" step of the process.
 
 For the $0 script to work, you must have the gtk_win32 files
-installed on your system in very specific locations.  Edit $0
-to change these.  While you are at it, feel free to provide a
-patch to improve the documentation about those libraries.
+as well as gdlib installed on your system in very specific
+locations.  Edit $0 to change these.  While you are at it, feel
+free to provide a patch to improve the documentation about 
+those libraries.
 
 EOF
 }
 
 debug=no
+do_autogen=no
 do_config=yes
 do_build=yes
+do_clean=yes
 do_install=yes
+config_args=""
 while test $# -ne 0 ; do
 	case $1 in
 		--debug)
+			if test "X${debug}" = "Xyes" ; then
+				config_args="${config_args} --enable-debug"
+			fi
 			debug=yes
 			shift
 			;;
@@ -90,8 +68,18 @@ while test $# -ne 0 ; do
 			exit 0
 			;;
 
+		--force-autogen)
+			do_autogen=yes
+			shift
+			;;
+
 		--skip-build)
 			do_build=no
+			shift
+			;;
+
+		--skip-clean)
+			do_clean=no
 			shift
 			;;
 
@@ -117,6 +105,14 @@ while test $# -ne 0 ; do
 	esac
 done
 
+if test ! -f win32/build_wcalc ; then
+	echo "$0:  ERROR.  This script must be run from the top level of the wcalc source tree."
+	exit 1
+fi
+
+# Run this under cygwin to build wcalc and create a windows installer for
+# it.  Thanks to Bob Paddock for pointing me to NSIS and answering some 
+# beginner windows questions.
 
 # where gtk_win32 is installed
 gtk_win32=c:\\cygwin\\home\\${USER}\\gtk_win32
@@ -125,11 +121,13 @@ gtk_win32=c:\\cygwin\\home\\${USER}\\gtk_win32
 gtk_win32_runtime=c:\\\\cygwin\\\\home\\\\${USER}\\\\gtk_win32_runtime
 
 # wcalc version
-wcalc_version=`awk '/AM_INIT_AUTOMAKE/ {gsub(/.*,[ \t]*/, ""); gsub(/\).*/, ""); print}' configure.ac `
+
+wcalc_version=`awk '/AC_INIT/ {gsub(/.*,[ \t]*\[/, ""); gsub(/\]\).*/, ""); print}' configure.ac`
 echo "wcalc_version=${wcalc_version}"
 
 # location of the NSIS makensis executible (see http://nsis.sourceforge.net)
 makensis="/cygdrive/c/Program Files/NSIS/makensis.exe"
+
 
 # ########################################################################
 #
@@ -137,6 +135,11 @@ makensis="/cygdrive/c/Program Files/NSIS/makensis.exe"
 #
 # ########################################################################
 
+
+if test ! -f configure -o $do_autogen = yes ; then
+	echo "Bootstrapping autotools"
+	ACLOCAL_FLAGS="-I ${gtk_win32}\\share\\aclocal" ./autogen.sh
+fi
 
 # source directory
 srcdir=`pwd.exe`/win32
@@ -155,35 +158,87 @@ wcalc_inst_dir=c:\\\\cygwin`echo ${wcalc_inst} | sed 's;/;\\\\\\\\;g'`
 PKG_CONFIG_PATH=${gtk_win32}\\lib\\pkgconfig
 export PKG_CONFIG_PATH
 
-PATH=${gtk_win32}\\bin:${PATH}
+PATH=${gtk_win32}\\bin:${gd_win32}:${PATH}
 export PATH
 
 echo "Showing packages known to pkg-config:"
 pkg-config --list-all
 
-if test "$do_config" = "yes" ; then
-echo "Configuring for cygwin"
-./configure \
-	--prefix=${wcalc_inst} \
-	--enable-gtk2 \
-	--disable-cgi \
-	--disable-htdocs \
-	--disable-nls \
-	--disable-stdio \
-	--without-matlab \
-	--without-octave \
-	--without-scilab \
-	2>&1 | tee c.log
+# add the gcc options to produce a native windows binary that
+# does not need cygwin to run
+if test "x${debug}" = "xno" ; then
+	EXTRA_FLAGS="-mwindows"
+fi
 
+CYGWIN_CFLAGS="-mms-bitfields -mno-cygwin ${EXTRA_FLAGS}"
+export CYGWIN_CFLAGS
+
+CYGWIN_CPPFLAGS="-mms-bitfields -mno-cygwin ${EXTRA_FLAGS}"
+export CYGWIN_CPPFLAGS
+
+# setting WIN32=yes will make sure that the desktop icon
+# gets compiled in
+if test "$do_config" = "yes" ; then
+rm -fr src/.deps
+echo "Configuring for cygwin"
+( ( ( env WIN32=yes \
+	./configure \
+	--prefix=${wcalc_inst} \
+	--disable-dependency-tracking \
+	--disable-nls \
+	--disable-update-desktop-database \
+	--disable-update-mime-database \
+	${config_args} \
+	WIN32=yes \
+	2>&1 ; echo $? >&4 ) | tee c.log 1>&3) 4>&1 | (read a ; exit $a)) 3>&1
+
+if test $? -ne 0 ; then
+	echo "**** ERROR **** Configure failed. See log in c.log"
+	exit 1
+fi
+
+# If the win32 pkg-config is used, then you end up with spurious CR's
+# in the generated Makefile's and we need to get rid of them.
+
+echo "Removing spurious carriage returns in the Makefiles..."
+for f in `find . -name Makefile -print` ; do
+	mv $f $f.bak
+	cat $f.bak | tr '\r' ' ' > $f
+	rm $f.bak
+done
+
+fi
+
+if test "$do_clean" = "yes" ; then
+echo "Cleaning"
+( ( ( make clean 2>&1 ; echo $? >&4) | tee clean.log 1>&3) 4>&1 | (read a ; exit $a) ) 3>&1
+if test $? -ne 0 ; then
+	echo "**** ERROR **** Clean failed. See log in clean.log"
+	exit 1
+fi
 fi
 
 if test "$do_build" = "yes" ; then
 echo "Building for cygwin"
-make 2>&1 | tee m.log
+( ( ( make 2>&1 ; echo $? >&4) | tee m.log 1>&3) 4>&1 | (read a ; exit $a) ) 3>&1
+if test $? -ne 0 ; then
+	echo "**** ERROR **** Build failed. See log in m.log"
+	exit 1
+fi
+fi
 
+if test "$do_install" = "yes" ; then
 echo "Installing for cygwin"
-make install 2>&1 | tee -a m.log
-
+# first clean out the installation directory to make sure
+# we don't have old junk lying around.
+if test -d ${wcalc_inst} ; then
+	rm -fr ${wcalc_inst}
+fi
+( ( ( make install 2>&1 ; echo $? >&4) | tee -a m.log 1>&3) 4>&1 | (read a ; exit $a) ) 3>&1
+if test $? -ne 0 ; then
+	echo "**** ERROR **** Build failed. See log in m.log"
+	exit 1
+fi
 fi
 
 echo "Creating NSIS script"
@@ -201,6 +256,7 @@ sed \
 
 echo "Creating windows installer"
 "${makensis}" ${src_dir}/wcalc.nsi
+
 
 echo "Windows installer left in ${srcdir}:"
 ls -l ${srcdir}/*.exe
