Another mac fix

diff --git a/ci-scripts/xvfb-run b/ci-scripts/xvfb-run
--- a/ci-scripts/xvfb-run
+++ b/ci-scripts/xvfb-run
@@ -98,17 +98,17 @@ clean_up() {
 }
 
 # Parse the command line.
-ARGS=$(getopt --options +ae:f:hn:lp:s:w: \
-       --long auto-servernum,error-file:,auth-file:,help,server-num:,listen-tcp,xauth-protocol:,server-args:,wait: \
-       --name "$PROGNAME" -- "$@")
-GETOPT_STATUS=$?
+# ARGS=$(getopt --options +ae:f:hn:lp:s:w: \
+#        --long auto-servernum,error-file:,auth-file:,help,server-num:,listen-tcp,xauth-protocol:,server-args:,wait: \
+#        --name "$PROGNAME" -- "$@")
+# GETOPT_STATUS=$?
 
-if [ $GETOPT_STATUS -ne 0 ]; then
-    error "internal error; getopt exited with status $GETOPT_STATUS"
-    exit 6
-fi
+# if [ $GETOPT_STATUS -ne 0 ]; then
+#     error "internal error; getopt exited with status $GETOPT_STATUS"
+#     exit 6
+# fi
 
-eval set -- "$ARGS"
+# eval set -- "$ARGS"
 
 while :; do
     case "$1" in
